version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asd123
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nextcloud_data:/var/www/html
      - ./aria2_download:/user-files:rw
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS='192.168.*.* cloud.hal2000.xyz'
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html
      - ./aria2_download:/user-files:rw
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  aria2:
    image: wahyd4/aria2-ui:nextcloud
    restart: always
    ports:
      - "9080:80"
      - "9443:443"
      - "6800:6800"
    volumes:
      - ./aria2_download:/user-files:rw
#    volumes:
#      - /some_folder:/root/conf/key
#      - ~/test/aria2.conf:/root/conf/aria2.conf
    environment:
      - DOMAIN=:80
      - ARIA2_USER=hh
      - ARIA2_PWD=asd123
      - ENABLE_AUTH=true
#      - SSL=true
#      - RPC_SECRET=Hello


  frpc:
    image: cloverzrg/frpc-docker
    restart: always
    network_mode: host
    volumes:
      - ./frpc.ini:/conf/frpc.ini

